apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp
spec:
  #NOT SUPER SURE HERE
  selector:
    matchLabels:
      app: my-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: my-webapp
  #############
  spec:
    containers:
    - name: my-webapp
      image: my-webapp-image
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: ./data/db:/data/db
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc