services:
  web:
    image: python:3.8-slim-buster
    command: docker build -t flask-docker .
    #command: docker run -d -p 5000:5000 flask-docker
    ports:
      -5000:5000
    working_dir: /flask-docker
    volumes:
      - .:/code

