version: '3'
services:
  flask:
    build: .
    image: todo
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    environment:
      MONGO_HOST: db
      MONGO_PORT: 27017
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db