#MONGODB DEPLOYMENT PODS YAML

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-pod
spec:
  #NOT SUPER SURE HERE
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: ccbd-todo-app-db-1
        image: mongo #:latest #/ccbd-todo-app-db-1 #mongo
        ports:
          - containerPort: 27017
        resources:
            limits:
              cpu: "0.5"
              memory: "128Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
        # volumeMounts:
        #   - name: mongodb-persistent-storage
        #     mountPath: ./data/db:/data/db
      # volumes:
      # - name: mongodb-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: mongodb-pvc\
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: db
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017
    targetPort: 27017
  type: LoadBalancer
#volumes path for mongo: ./data/db:/data/db
          #for flask: ./data:/data, port 5000:5000






